"""End-to-end verification harness for the `jira-analyzer` agent.

Invokes the real `claude` CLI per fixture (same path `scoring_service.score_pending`
uses) and asserts that the agent picks the right `skill_name` on canonical
plan shapes and returns `null` on negatives. Quality/AI scores are sanity-
checked only — the agent has discretion there.

Replaces the deleted Python-regex harness (`verify_skill_detection.py`). Each
scenario is one CLI subprocess call, so this run costs real tokens. The
default model is whatever the agent frontmatter specifies; pass `--model` to
override (e.g. `--model claude-opus-4-7` for calibration).

Usage (from project root):
    .jira-analytics/bin/python backend/cli/verify_jira_analyzer.py
    .jira-analytics/bin/python backend/cli/verify_jira_analyzer.py --only "canonical backend plan"
    .jira-analytics/bin/python backend/cli/verify_jira_analyzer.py --model claude-opus-4-7
"""
from __future__ import annotations

import logging
import sys
from dataclasses import dataclass
from pathlib import Path
from types import SimpleNamespace

import click
from dotenv import load_dotenv

_BACKEND_DIR = Path(__file__).resolve().parents[1]
if str(_BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(_BACKEND_DIR))

_PROJECT_ROOT = _BACKEND_DIR.parent
load_dotenv(_PROJECT_ROOT / ".env")

from app.services.scoring_service import (  # noqa: E402
    _build_user_prompt,
    _invoke_claude,
    _load_agent,
    _parse_score_json,
)


# ---- canonical-shape fixtures ----------------------------------------------

CANONICAL_BE_PLAN = """# Implementation Plan: Add company payroll snapshot endpoint
<!-- Source: jira-requirement.txt | Generated by /prepare-dev-plan -->

## Goal
Expose a new endpoint that returns the current payroll snapshot for a company.

## Acceptance Criteria
- Endpoint returns 200 with the snapshot DTO.
- Requires `@PreAuthorize` on the controller.

## Affected Modules
| Module | Role |
|---|---|
| lumberfi-db | new entity + liquibase changelog |
| lumberfi-api | controller + service |

## Architecture Notes
Uses the canonical Converter singleton pattern.

## Phase 1 — DB / Entity Changes
### Files
- lumberfi-db/src/main/resources/liquibase/changelog/app/changes/XXXXXX-payroll-snapshot.sql

### Implementation Details
Define the entity. Avoid `@Data` on the JPA entity.

### DB Changes (if applicable)
Add the table `payroll_snapshot`.

### Testing
Unit: PayrollSnapshotServiceTest — cover: basic save/load
Integration: PayrollSnapshotIT — cover: end-to-end fetch

## Phase 2 — Service Layer
### Files
- lumberfi-api/src/main/java/.../PayrollSnapshotService.java

### Implementation Details
`@Transactional(readOnly=true)` on reads.

### Testing
Unit: PayrollSnapshotServiceTest

## Conventions Reminder
- No `@Data` on JPA entities
- All new DTOs must use `*DTO` suffix
- Prevent N+1 queries
"""


CANONICAL_FE_PLAN = """# Implementation Plan: Project list filters
<!-- Source: jira-requirement.txt | Generated by /lfi-prepare-dev-plan -->

## Goal
Add filters to the project list screen.

## Acceptance Criteria
| # | Criterion |
|---|---|
| 1 | User can filter by status |

## Affected Areas
| Path | Role |
|---|---|
| src/screens/Projects/ | screen + filter UI |
| src/api/projects/ | new API call |
| src/models/projectsModel.ts | easy-peasy state |

## Architecture Notes
| Concern | Applies | Notes |
|---|---|---|
| New route / Launcher entry | No | _None_ |
| Global state (Easy Peasy model) | Yes | filter state |

## Phase 1 — Types & Constants
### Files
| Path | Change type | What changes |
|---|---|---|
| src/types/projects/filters.ts | NEW | filter types |

### Implementation Details
_None_

### Types & DTOs
| Name | Kind | Fields / Members | Notes |
|---|---|---|---|
| ProjectFilter | interface | status, search | _None_ |

### API Changes
| Function | Method | URL | baseURL | Auth | Request | Response | Cancel token |
|---|---|---|---|---|---|---|---|
| apiGetProjects | GET | /projects | platformApiUrl | getPlatformHeaders() | filter | list | yes |

### State / Store Changes
| Model file | Change type | Actions | Thunks | Selectors | Subscribers |
|---|---|---|---|---|---|
| src/models/projectsModel.ts | MODIFIED | setFilter | fetchProjects | filteredProjects | _None_ |

### Components & Hooks
_None_

### Tests
| Type | File | Key scenarios |
|---|---|---|
| Unit | __tests__/projectsModel.test.ts | filter applied |

## Conventions Reminder
| # | Rule | Source |
|---|---|---|
| 1 | Use easy-peasy thunks | docs/ai-context/state.md |
"""


CANONICAL_APP_PLAN = """# Implementation Plan: Timesheet offline sync indicator
<!-- Source: jira-requirement.txt | Generated by /lfi-prepare-dev-plan -->

## Goal
Show offline sync state on the timesheet screen.

## Acceptance Criteria
| # | Criterion |
|---|---|
| 1 | Indicator visible when offline |

## Affected Areas
| Path | Role |
|---|---|
| src/screens/Timesheet/Components/ | new indicator component |
| App.tsx | RootStackParamList unchanged |
| src/services/offlineMode/repositories/timesheet.ts | offline flag |

## Architecture Notes
Targets the LumberFI RN/Expo codebase. Uses Easy Peasy model for global state.

## Phase 1 — Types & Constants
### Files
| Path | Change type | What changes |
|---|---|---|
| src/types/timesheet/offline.ts | NEW | offline status enum |

### Implementation Details
react-native AppState listener.

### Types & DTOs
_None_

### API Changes
_None_

### State / Store Changes
_None_

### Components & Hooks
| Name | Kind | Path | Props / Signature | Responsibility | Memoization |
|---|---|---|---|---|---|
| OfflineBadge | Presentational | src/screens/Timesheet/Components/OfflineBadge.tsx | { online: bool } | show badge | memo |

### Tests
| Type | File | Key scenarios |
|---|---|---|
| Component | __tests__/OfflineBadge.test.tsx | renders when offline |

## Conventions Reminder
| # | Rule | Source |
|---|---|---|
| 1 | Check lumberfi-app-components first | docs/ai-context/components.md |
"""


# ---- negative fixtures -----------------------------------------------------

GENERIC_MARKDOWN_TICKET = """# Bug: dashboard breaks on Safari

Repro:
1. Open the dashboard on Safari 17.
2. Click any row.

## Phase 1
Try a fix.
"""


EDITED_PLAN_NO_H1 = """## Goal
Add filters to the project list.

<!-- Source: jira-requirement.txt | Generated by /lfi-prepare-dev-plan -->

## Phase 1 — Types
src/screens/Projects/ change.
"""


PLAN_COMMENT_NO_PLATFORM = """# Implementation Plan: Refactor button styles
<!-- Source: jira-requirement.txt | Generated by /lfi-prepare-dev-plan -->

## Goal
Tidy up.

## Phase 1 — Cleanup
General work, no platform-specific paths or API references.
"""


AMBIGUOUS_FE_APP_PLAN = """# Implementation Plan: Shared API client
<!-- Source: jira-requirement.txt | Generated by /lfi-prepare-dev-plan -->

## Phase 1 — API
platformApiUrl on web. react-native on mobile.
"""


EMPTY = ""
NONE_DESC = None


# ---- harness ---------------------------------------------------------------


@dataclass
class Scenario:
    name: str
    description: str | None
    story_points: float | None
    expected_skill: str | None  # None means "either null or low-confidence"
    skill_must_match: bool      # True for canonical fixtures; False for negatives


SCENARIOS: list[Scenario] = [
    Scenario("canonical backend plan", CANONICAL_BE_PLAN, 5.0, "BE_Skill", True),
    Scenario("canonical FE plan", CANONICAL_FE_PLAN, 3.0, "FE_Skill", True),
    Scenario("canonical APP plan", CANONICAL_APP_PLAN, 3.0, "APP_Skill", True),
    Scenario("generic markdown ticket", GENERIC_MARKDOWN_TICKET, 1.0, None, True),
    Scenario("edited plan missing H1", EDITED_PLAN_NO_H1, 3.0, None, True),
    Scenario("plan comment but no platform markers", PLAN_COMMENT_NO_PLATFORM, 2.0, None, True),
    Scenario("ambiguous FE/APP plan", AMBIGUOUS_FE_APP_PLAN, 2.0, None, True),
    Scenario("empty description", EMPTY, 1.0, None, True),
    Scenario("none description", NONE_DESC, 1.0, None, True),
]


def _fake_issue(sc: Scenario, idx: int) -> SimpleNamespace:
    return SimpleNamespace(
        jira_key=f"VERIFY-{idx:03d}",
        issue_type="Story",
        summary=sc.name,
        story_points=sc.story_points,
        description=sc.description,
    )


@click.command()
@click.option("--model", default=None, help="Override the agent's frontmatter model")
@click.option("--timeout", default=None, type=int, help="Per-call timeout in seconds (default 600)")
@click.option("--only", default=None, help="Substring filter — run only matching scenarios")
@click.option("-v", "--verbose", is_flag=True)
def main(model: str | None, timeout: int | None, only: str | None, verbose: bool) -> None:
    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.WARNING,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    agent_body, allowed_tools, agent_model = _load_agent()
    chosen_model = model or agent_model
    timeout_secs = timeout or 600

    scenarios = [s for s in SCENARIOS if (only is None or only.lower() in s.name.lower())]
    if not scenarios:
        click.echo(f"no scenarios match --only={only!r}", err=True)
        sys.exit(2)

    click.echo(
        f"running {len(scenarios)} scenarios against jira-analyzer "
        f"(model={chosen_model or 'agent default'})"
    )

    failures = 0
    for idx, sc in enumerate(scenarios, start=1):
        issue = _fake_issue(sc, idx)
        user_prompt = _build_user_prompt(issue)

        try:
            cli_result = _invoke_claude(
                agent_body=agent_body,
                allowed_tools=allowed_tools,
                user_prompt=user_prompt,
                model=chosen_model,
                timeout=timeout_secs,
            )
            parsed = _parse_score_json(cli_result.text)
        except Exception as exc:  # noqa: BLE001
            click.echo(f"[FAIL] {sc.name:<42} ERROR: {exc}", err=True)
            failures += 1
            continue

        got_skill = parsed.get("skill_name")
        got_q = parsed.get("quality_score")
        got_ai = parsed.get("ai_score")

        skill_ok = (got_skill == sc.expected_skill) if sc.skill_must_match else True
        sane_ranges = (
            isinstance(got_q, (int, float)) and 0 <= got_q <= 5
            and isinstance(got_ai, (int, float)) and 0 <= got_ai <= 5
        )
        ok = skill_ok and sane_ranges
        if not ok:
            failures += 1

        status = "PASS" if ok else "FAIL"
        click.echo(
            f"[{status}] {sc.name:<42} "
            f"expected_skill={sc.expected_skill!s:<10} got_skill={got_skill!s:<10} "
            f"q={got_q} ai={got_ai}"
        )
        if not ok and verbose:
            click.echo(f"        quality_reason={parsed.get('quality_reason')!r}")
            click.echo(f"        ai_reason={parsed.get('ai_reason')!r}")

    click.echo("---")
    click.echo(f"{len(scenarios) - failures}/{len(scenarios)} scenarios passed")
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
