"""initial_schema

Revision ID: 000100
Revises: 
Create Date: 2026-05-11 12:32:48.715563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '000100'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_integrations_kind_active', 'integrations', ['kind', 'is_active'], unique=False)
    op.create_table('sprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_sprint_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('complete_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_sprint_id')
    )
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issues_synced', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(), nullable=True),
    sa.Column('sync_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_state_started_at', 'sync_state', ['started_at'], unique=False)
    op.create_index('idx_sync_state_status', 'sync_state', ['status'], unique=False)
    op.create_index('idx_sync_state_sync_group_id', 'sync_state', ['sync_group_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_team_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_team_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_account_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_account_id')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_key', sa.String(), nullable=False),
    sa.Column('jira_issue_id', sa.String(), nullable=True),
    sa.Column('project', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_adf', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('issue_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('epic_key', sa.String(), nullable=True),
    sa.Column('story_points', sa.Numeric(), nullable=True),
    sa.Column('time_estimate_secs', sa.Integer(), nullable=True),
    sa.Column('time_spent_secs', sa.Integer(), nullable=True),
    sa.Column('labels', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('components', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('fix_versions', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('customers', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('reported_by_customer', sa.Boolean(), nullable=True),
    sa.Column('prod_release_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_issue_id'),
    sa.UniqueConstraint('jira_key')
    )
    op.create_index('idx_issues_assignee', 'issues', ['assignee_id'], unique=False)
    op.create_index('idx_issues_created_at', 'issues', ['created_at'], unique=False)
    op.create_index('idx_issues_epic_key', 'issues', ['epic_key'], unique=False)
    op.create_index('idx_issues_issue_type', 'issues', ['issue_type'], unique=False)
    op.create_index('idx_issues_project', 'issues', ['project'], unique=False)
    op.create_index('idx_issues_status', 'issues', ['status'], unique=False)
    op.create_index('idx_issues_team', 'issues', ['team_id'], unique=False)
    op.create_table('staging_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_key', sa.String(), nullable=False),
    sa.Column('sync_state_id', sa.Integer(), nullable=False),
    sa.Column('jira_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_status', sa.String(), server_default='pending', nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sync_state_id'], ['sync_state.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_staging_change_type_status', 'staging_issues', ['change_type', 'review_status'], unique=False)
    op.create_index('idx_staging_key_id', 'staging_issues', ['jira_key', 'id'], unique=False)
    op.create_index('idx_staging_review_status', 'staging_issues', ['review_status'], unique=False)
    op.create_index('idx_staging_sync_key', 'staging_issues', ['sync_state_id', 'jira_key'], unique=True)
    op.create_index('uq_staging_active_jira_key', 'staging_issues', ['jira_key'], unique=True, postgresql_where=sa.text("review_status IN ('pending', 'approved')"))
    op.create_table('sync_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_state_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='running', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('items_total', sa.Integer(), nullable=True),
    sa.Column('items_processed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sync_state_id'], ['sync_state.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_phases_heartbeat_running', 'sync_phases', ['heartbeat_at'], unique=False, postgresql_where=sa.text("status = 'running'"))
    op.create_index('idx_sync_phases_phase_status', 'sync_phases', ['phase', 'status'], unique=False)
    op.create_index('idx_sync_phases_sync_state', 'sync_phases', ['sync_state_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('jira_attachment_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('content_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_attachment_id')
    )
    op.create_index('idx_attachments_issue', 'attachments', ['issue_id'], unique=False)
    op.create_table('changelogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('from_value', sa.String(), nullable=True),
    sa.Column('to_value', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_changelogs_issue_field', 'changelogs', ['issue_id', 'field', 'changed_at'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('jira_comment_id', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_comment_id')
    )
    op.create_table('failed_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sync_state_id', sa.Integer(), nullable=True),
    sa.Column('staging_id', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), server_default='jira_to_lumber', nullable=False),
    sa.Column('jira_ref', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=False),
    sa.Column('fix_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_retried_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity IN ('issue', 'user', 'sprint', 'comment', 'attachment', 'team')", name='ck_failed_records_entity'),
    sa.CheckConstraint("error_code IN ('DEPENDENCY', 'CONFLICT_UNIQUE', 'CONFLICT_FIELDS', 'VALIDATION', 'RATE_LIMITED', 'NETWORK', 'TIMEOUT', 'UNKNOWN')", name='ck_failed_records_error_code'),
    sa.CheckConstraint("phase IN ('sync', 'promote', 'sanitize', 'score')", name='ck_failed_records_phase'),
    sa.ForeignKeyConstraint(['staging_id'], ['staging_issues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sync_state_id'], ['sync_state.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_failed_code', 'failed_records', ['error_code'], unique=False)
    op.create_index('idx_failed_entity_ref', 'failed_records', ['entity', 'jira_ref'], unique=False)
    op.create_index('idx_failed_open', 'failed_records', [sa.text('created_at DESC')], unique=False, postgresql_where=sa.text('dismissed_at IS NULL'))
    op.create_index('idx_failed_sync', 'failed_records', ['sync_state_id'], unique=False)
    op.create_table('issue_ai_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('scoring_status', sa.String(), server_default='pending', nullable=False),
    sa.Column('description_hash', sa.String(length=64), nullable=True),
    sa.Column('description_quality_score', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('ai_plan_detected', sa.Boolean(), nullable=True),
    sa.Column('skill_usage_detected', sa.Boolean(), nullable=True),
    sa.Column('skill_name', sa.String(), nullable=True),
    sa.Column('complexity_estimate', sa.String(), nullable=True),
    sa.Column('scoring_notes', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id')
    )
    op.create_index('idx_ai_scores_issue', 'issue_ai_scores', ['issue_id'], unique=False)
    op.create_index('idx_ai_scores_status', 'issue_ai_scores', ['scoring_status'], unique=False)
    op.create_table('issue_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('cycle_time_hours', sa.Numeric(), nullable=True),
    sa.Column('lead_time_hours', sa.Numeric(), nullable=True),
    sa.Column('time_in_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reopen_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id')
    )
    op.create_table('issue_sprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id', 'sprint_id', name='uq_issue_sprints_issue_sprint')
    )
    op.create_index('idx_issue_sprints_issue', 'issue_sprints', ['issue_id'], unique=False)
    op.create_index('idx_issue_sprints_sprint', 'issue_sprints', ['sprint_id'], unique=False)
    op.create_table('worklogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('jira_worklog_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent_secs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_adf', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_worklog_id')
    )
    op.create_index('idx_worklogs_author_started', 'worklogs', ['author_id', 'started_at'], unique=False)
    op.create_index('idx_worklogs_issue_started', 'worklogs', ['issue_id', 'started_at'], unique=False)
    # ### end Alembic commands ###

    # ---- analytics views (raw SQL; not autogenerated) ----

    op.execute(
        """
        CREATE OR REPLACE VIEW v_issue_facts AS
        SELECT
            i.id                              AS issue_id,
            i.jira_key,
            i.project,
            i.summary,
            i.issue_type,
            i.status,
            i.priority,
            i.epic_key,
            i.story_points,
            i.time_estimate_secs,
            i.time_spent_secs,
            CASE
                WHEN i.time_estimate_secs IS NOT NULL
                THEN i.time_estimate_secs::numeric / 3600.0
            END                               AS estimate_hours,
            CASE
                WHEN i.time_spent_secs IS NOT NULL
                THEN i.time_spent_secs::numeric / 3600.0
            END                               AS spent_hours,
            (i.description IS NULL OR length(trim(i.description)) = 0) AS no_description,
            CASE
                WHEN i.time_estimate_secs IS NOT NULL
                 AND i.time_spent_secs IS NOT NULL
                 AND i.time_estimate_secs > 0
                 AND i.time_spent_secs > i.time_estimate_secs
                THEN TRUE
                ELSE FALSE
            END                               AS over_budget,
            (lower(coalesce(i.status, '')) IN ('done', 'closed', 'resolved', 'completed'))
                                              AS is_done,
            i.assignee_id,
            ua.display_name                   AS assignee_name,
            ua.email                          AS assignee_email,
            i.team_id,
            t.name                            AS team_name,
            t.jira_team_id,
            i.created_at,
            i.updated_at,
            i.resolved_at,
            i.synced_at,
            ais.scoring_status                AS ai_scoring_status,
            ais.description_quality_score     AS quality_score,
            ais.ai_plan_detected,
            ais.skill_usage_detected,
            ais.skill_name,
            ais.complexity_estimate,
            ais.model_used                    AS scoring_model,
            ais.scored_at,
            ais.input_tokens,
            ais.output_tokens,
            ais.cache_read_tokens,
            im.cycle_time_hours,
            im.lead_time_hours,
            im.reopen_count,
            im.comment_count
        FROM issues i
        LEFT JOIN users ua            ON ua.id = i.assignee_id
        LEFT JOIN teams t             ON t.id = i.team_id
        LEFT JOIN issue_ai_scores ais ON ais.issue_id = i.id
        LEFT JOIN issue_metrics im    ON im.issue_id = i.id
        ;
        """
    )

    op.execute(
        """
        CREATE OR REPLACE VIEW v_team_aggregates AS
        SELECT
            f.team_id,
            f.team_name,
            f.jira_team_id,
            COUNT(*)                                                    AS issue_count,
            AVG(f.quality_score)                                        AS avg_quality,
            COUNT(*) FILTER (WHERE f.quality_score IS NOT NULL)         AS scored_count,
            SUM(f.story_points)                                         AS total_story_points,
            AVG(f.story_points)                                         AS avg_story_points,
            AVG(f.estimate_hours)                                       AS avg_estimate_hours,
            AVG(f.spent_hours)                                          AS avg_spent_hours,
            COUNT(*) FILTER (WHERE f.skill_usage_detected IS TRUE)      AS skill_count,
            COUNT(*) FILTER (WHERE f.no_description)                    AS no_description_count,
            COUNT(*) FILTER (WHERE f.over_budget)                       AS over_budget_count,
            COUNT(*) FILTER (WHERE f.ai_plan_detected IS TRUE)          AS ai_plan_count
        FROM v_issue_facts f
        WHERE f.team_id IS NOT NULL
        GROUP BY f.team_id, f.team_name, f.jira_team_id
        ;
        """
    )

    op.execute(
        """
        CREATE OR REPLACE VIEW v_assignee_aggregates AS
        SELECT
            f.assignee_id,
            f.assignee_name,
            f.assignee_email,
            f.team_id,
            f.team_name,
            COUNT(*)                                                    AS issue_count,
            AVG(f.quality_score)                                        AS avg_quality,
            COUNT(*) FILTER (WHERE f.quality_score IS NOT NULL)         AS scored_count,
            SUM(f.story_points)                                         AS total_story_points,
            AVG(f.story_points)                                         AS avg_story_points,
            AVG(f.estimate_hours)                                       AS avg_estimate_hours,
            AVG(f.spent_hours)                                          AS avg_spent_hours,
            COUNT(*) FILTER (WHERE f.skill_usage_detected IS TRUE)      AS skill_count,
            COUNT(*) FILTER (WHERE f.no_description)                    AS no_description_count,
            COUNT(*) FILTER (WHERE f.over_budget)                       AS over_budget_count,
            COUNT(*) FILTER (WHERE f.ai_plan_detected IS TRUE)          AS ai_plan_count
        FROM v_issue_facts f
        WHERE f.assignee_id IS NOT NULL
        GROUP BY f.assignee_id, f.assignee_name, f.assignee_email, f.team_id, f.team_name
        ;
        """
    )

    op.execute(
        """
        CREATE OR REPLACE VIEW v_sprint_velocity AS
        SELECT
            s.id                                                AS sprint_id,
            s.jira_sprint_id,
            s.name                                              AS sprint_name,
            s.state                                             AS sprint_state,
            s.start_date,
            s.end_date,
            s.complete_date,
            COUNT(isp.issue_id)                                 AS issue_count,
            SUM(i.story_points)                                 AS planned_points,
            SUM(i.story_points) FILTER (
                WHERE lower(coalesce(i.status, '')) IN ('done', 'closed', 'resolved', 'completed')
            )                                                   AS completed_points,
            COUNT(*) FILTER (
                WHERE lower(coalesce(i.status, '')) IN ('done', 'closed', 'resolved', 'completed')
            )                                                   AS completed_count,
            CASE
                WHEN SUM(i.story_points) > 0
                THEN (
                    SUM(i.story_points) FILTER (
                        WHERE lower(coalesce(i.status, '')) IN ('done', 'closed', 'resolved', 'completed')
                    )
                ) / SUM(i.story_points)
                ELSE NULL
            END                                                 AS completion_pct
        FROM sprints s
        LEFT JOIN issue_sprints isp ON isp.sprint_id = s.id
        LEFT JOIN issues i          ON i.id = isp.issue_id
        GROUP BY s.id, s.jira_sprint_id, s.name, s.state, s.start_date, s.end_date, s.complete_date
        ;
        """
    )

    op.execute(
        """
        CREATE OR REPLACE VIEW v_epic_progress AS
        SELECT
            i.epic_key,
            i.project,
            COUNT(*)                                                                  AS total_count,
            COUNT(*) FILTER (
                WHERE lower(coalesce(i.status, '')) IN ('done', 'closed', 'resolved', 'completed')
            )                                                                         AS done_count,
            COUNT(*) FILTER (WHERE lower(coalesce(i.issue_type, '')) = 'bug')         AS bug_count,
            SUM(i.story_points)                                                       AS points_total,
            SUM(i.story_points) FILTER (
                WHERE lower(coalesce(i.status, '')) IN ('done', 'closed', 'resolved', 'completed')
            )                                                                         AS points_done,
            CASE
                WHEN COUNT(*) > 0
                THEN COUNT(*) FILTER (
                    WHERE lower(coalesce(i.status, '')) IN ('done', 'closed', 'resolved', 'completed')
                )::numeric / COUNT(*)
                ELSE NULL
            END                                                                       AS completion_pct
        FROM issues i
        WHERE i.epic_key IS NOT NULL
        GROUP BY i.epic_key, i.project
        ;
        """
    )


VIEWS = (
    "v_epic_progress",
    "v_sprint_velocity",
    "v_assignee_aggregates",
    "v_team_aggregates",
    "v_issue_facts",
)


def downgrade() -> None:
    for v in VIEWS:
        op.execute(f"DROP VIEW IF EXISTS {v} CASCADE;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_worklogs_issue_started', table_name='worklogs')
    op.drop_index('idx_worklogs_author_started', table_name='worklogs')
    op.drop_table('worklogs')
    op.drop_index('idx_issue_sprints_sprint', table_name='issue_sprints')
    op.drop_index('idx_issue_sprints_issue', table_name='issue_sprints')
    op.drop_table('issue_sprints')
    op.drop_table('issue_metrics')
    op.drop_index('idx_ai_scores_status', table_name='issue_ai_scores')
    op.drop_index('idx_ai_scores_issue', table_name='issue_ai_scores')
    op.drop_table('issue_ai_scores')
    op.drop_index('idx_failed_sync', table_name='failed_records')
    op.drop_index('idx_failed_open', table_name='failed_records', postgresql_where=sa.text('dismissed_at IS NULL'))
    op.drop_index('idx_failed_entity_ref', table_name='failed_records')
    op.drop_index('idx_failed_code', table_name='failed_records')
    op.drop_table('failed_records')
    op.drop_table('comments')
    op.drop_index('idx_changelogs_issue_field', table_name='changelogs')
    op.drop_table('changelogs')
    op.drop_index('idx_attachments_issue', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('idx_sync_phases_sync_state', table_name='sync_phases')
    op.drop_index('idx_sync_phases_phase_status', table_name='sync_phases')
    op.drop_index('idx_sync_phases_heartbeat_running', table_name='sync_phases', postgresql_where=sa.text("status = 'running'"))
    op.drop_table('sync_phases')
    op.drop_index('uq_staging_active_jira_key', table_name='staging_issues', postgresql_where=sa.text("review_status IN ('pending', 'approved')"))
    op.drop_index('idx_staging_sync_key', table_name='staging_issues')
    op.drop_index('idx_staging_review_status', table_name='staging_issues')
    op.drop_index('idx_staging_key_id', table_name='staging_issues')
    op.drop_index('idx_staging_change_type_status', table_name='staging_issues')
    op.drop_table('staging_issues')
    op.drop_index('idx_issues_team', table_name='issues')
    op.drop_index('idx_issues_status', table_name='issues')
    op.drop_index('idx_issues_project', table_name='issues')
    op.drop_index('idx_issues_issue_type', table_name='issues')
    op.drop_index('idx_issues_epic_key', table_name='issues')
    op.drop_index('idx_issues_created_at', table_name='issues')
    op.drop_index('idx_issues_assignee', table_name='issues')
    op.drop_table('issues')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_index('idx_sync_state_status', table_name='sync_state')
    op.drop_index('idx_sync_state_started_at', table_name='sync_state')
    op.drop_table('sync_state')
    op.drop_table('sprints')
    # ### end Alembic commands ###
